config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'static_pages/about', to: 'static_pages#about', as: 'about'
  # get '/patients/:id', to: 'patients#show', as: 'patient'


  # get :terms_of_use, to: 'pages#terms_of_use', path: 'terms-of-use'
  # get 'terms-of-use', to: :terms_of_use, controller: 'pages'

  root 'products#index'

  resources :products, only: [:show, :index]

  namespace :admin do
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { post :sort_products }
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_list add_new_at: :top
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    http_basic_authenticate_with name: ENV['ADMIN_USERNAME'],
                                 password: ENV['ADMIN_PASSWORD']

    def index
      @products = Product.order('position')
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = "#{@product.name} successfully created"
        redirect_to product_path(@product)
      else
        render 'new'
      end
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update_attributes(product_params)
        flash[:notice] = "#{@product.name} successfully updated"
        redirect_to product_path(@product)
      else
        render 'edit'
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      flash[:notice] = "#{@product.name} successfully deleted"
      redirect_to products_path
    end

    def sort_products
      params[:product].each_with_index do |id, index|
        Product.where(id: id).update_all(position: index + 1)
      end
      render nothing: true
    end

    private

    def product_params
      params.require(:product)
            .permit(:name, :image, :description, :price, :position)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('position')
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/products/edit.html.slim
 .row
  .col-md-6.col-md-offset-3

    h1 Update product

    = form_for [:admin, @product] do |f|

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :image
        = f.text_field :image, class: 'form-control'

      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'

      p
        = f.submit 'Update product', class: 'btn btn-default'


    p = link_to 'Back', root_path

app/views/admin/products/index.html.slim
#myModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title Success
      .modal-body
        p Record updated!
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close

h2 Home page

.alert.alert-info
  - if @products.count == 0
    p There are no products in database.
  - else
    p We have #{@products.count} products in our database.

ul#products-listing.list-group data-update-url=" #{sort_products_admin_products_path} "

  - @products.each do |product|
    = content_tag_for :li, product, class: 'list-group-item' do
      span.drag-handle = fa_icon "sort", class: "fa-lg"
      = link_to(product.name, product_path(product))

p = link_to 'Add new product', new_admin_product_path, class: 'btn btn-primary'

app/views/admin/products/new.html.slim
.row
  .col-md-6.col-md-offset-3

    h1 Create new product

    = form_for [:admin, @product] do |f|

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :image
        = f.text_field :image, class: 'form-control'

      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'

      p
        = f.submit 'Create product', class: 'btn btn-default'


    p = link_to 'Back', root_path

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar

      = link_to 'Records Sorting', root_path, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li = link_to 'Home', root_path
        li = link_to 'About', about_path
      ul.nav.navbar-nav.navbar-right
        li = link_to 'Admin', admin_products_path

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    meta name='keywords' content='template language'
    meta name='author' content='Josef Zacek'
    title Rails Records Sorting
    = csrf_meta_tags
    = favicon_link_tag '/favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body

    = render 'layouts/navbar'

    .container
      - if flash[:notice]
        .alert.alert-info
          p = flash[:notice]

      = yield

      hr

      footer
        p Created by #{link_to 'josefzacek.com', 'http://josefzacek.com'}

app/views/products/edit.html.slim
.row
  .col-md-6.col-md-offset-3

    h1 Update product

    = form_for @product do |f|

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :image
        = f.text_field :image, class: 'form-control'

      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'

      p
        = f.submit 'Update product', class: 'btn btn-default'


    p = link_to 'Back', root_path

app/views/products/index.html.slim
h2 Products listing

.alert.alert-info
  - if @products.count == 0
    p There are no products in database.
  - else
    p We have #{@products.count} products in our database.

- @products.in_groups_of(3, false).each do |group|
  .row
    - group.each do |product|
      .col-sm-6.col-md-4
        .thumbnail
          = link_to product_path(product), title: product.name do
            = image_tag(product.image, alt: product.name , class: 'img-responsive')
        .caption
          h3.text-center = product.name
          p = truncate(product.description, length: 92, omission: ' ...')
          p = link_to "View #{product.name} product", product_path(product), class: 'btn btn-primary'
          hr

app/views/products/new.html.slim
.row
  .col-md-6.col-md-offset-3

    h1 Create new product

    = form_for @product do |f|

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :image
        = f.text_field :image, class: 'form-control'

      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'

      p
        = f.submit 'Create product', class: 'btn btn-default'


    p = link_to 'Back', root_path

app/views/products/show.html.slim
h1 Product details

.row
  .col-md-6
    p
      b Name: 
      = @product.name

    p
      b Description: 
      = @product.description

    p
      b Price: 
      = @product.price

    .btn-group    
      = link_to 'Home page', root_path, class: 'btn btn-default'
      = link_to 'Edit product', edit_admin_product_path(@product), class: 'btn btn-default'
      = link_to 'Destroy',  admin_product_path(@product),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'

  .col-md-6
    p
      b = image_tag(@product.image, class: 'img-responsive center-block')

app/views/static_pages/about.html.slim
h2 About

p Application allows logged in user to Create, Update, Delete and Reorder records in database using Drag &amp; Drop functionality. 

h3 Screenshots


= image_tag '/admin-area.png', alt: 'Admin area'


= image_tag '/record-updated-modal.png', alt: 'Record updated modal'